apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: db
  labels:
    id: "924820"
    app: db
    env: dev
spec:
  selector:
    id: "924820"
    app: db
    env: dev
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306