apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: db
  labels:
    id: "924820"
    app: db
    env: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      id: "924820"
      app: db
      env: dev
  template:
    metadata:
      labels:
        id: "924820"
        app: db
        env: dev
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.6.4-focal
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootpassword
            - name: MYSQL_DATABASE
              value: wordpress
            - name: MYSQL_USER
              value: wpuser
            - name: MYSQL_PASSWORD
              value: wppassword
          ports:
            - containerPort: 3306