apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wp
  labels:
    id: "924820"   
    app: wp-app
    env: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      id: "924820"   
      app: wp-app
      env: dev
  template:
    metadata:
      labels:
        id: "924820"  
        app: wp-app
        env: dev
    spec:
      containers:
        - name: wordpress
          image: wordpress:latest
          env:
            - name: WORDPRESS_DB_HOST
              value: mariadb.db.svc.cluster.local
            - name: WORDPRESS_DB_USER
              value: wpuser
            - name: WORDPRESS_DB_PASSWORD
              value: wppassword
            - name: WORDPRESS_DB_NAME
              value: wordpress
          ports:
            - containerPort: 80
