---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: wp
  labels:
    id: "924820"   
    app: wp-app
    env: dev
spec:
  selector:
    id: "924820"   
    app: wp-app
    env: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      
      
      