apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
  namespace: proxy
  labels:
    id: "924820"
    app: proxy
    env: dev
spec:
  selector:
    id: "924820"
    app: proxy
    env: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
